<?php

namespace Src\Controllers;

class AdminController extends Controller
{
    protected function setLayout(): void
    {
        parent::setLayout(); // TODO: Change the autogenerated stub
    }

    public function getLayout(): string{
        $this->renderer->render('layout');
    }

}